language: node_js
node_js:
  - "iojs"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"

matrix:
  allow_failures:
    - node_js: "0.11"
    - node_js: "0.8"

before_install:
  - npm update -g npm
  - npm install -g grunt-cli

sudo: false
