language: node_js
node_js:
  - "iojs"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
matrix:
  allow_failures:
    - node_js: "0.11"
before_install:
  - "npm update -g npm"
  - "( pushd $(dirname `which npm`)/../lib/; npm update npm; popd; )"
  - "npm install -g grunt-cli"
